version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker: 
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: npm test 1.6.e2e.ts
      - run: npm test 1.6.unit.ts
